name: cocheras_nestle_web
description: "App web para administraciÃ³n de las Cocheras de la Empresa Nestle"
publish_to: "none" 
version: 1.0.0+1
environment:
  sdk: ^3.9.0
dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  go_router: ^16.2.4
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  google_fonts: ^6.3.2
  collection: ^1.17.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  